-- Contact Admin / support tickets. Run this once in the Supabase SQL editor
-- (Project -> SQL Editor -> New query -> paste -> Run), matching the pattern
-- used by pdf-store-setup.sql.

-- 1. Storage bucket for user-attached screenshots/documents.
insert into storage.buckets (id, name, public)
values ('support-attachments', 'support-attachments', false)
on conflict (id) do nothing;
-- Private bucket: attachments are only ever read via the service-role admin
-- client (signed URLs generated by api/support/admin.js's `list` action) —
-- never a public URL, since a bug-report screenshot may contain personal info.

-- 2. Tickets table
create table if not exists support_tickets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id),
  reporter_email text not null,
  subject text not null,
  message text not null,
  -- [{ path, name, contentType, size }] — path is the support-attachments
  -- storage object key uploaded via api/support/create-upload-url.js.
  attachments jsonb not null default '[]',
  status text not null default 'open', -- 'open' | 'resolved'
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table support_tickets enable row level security;
-- Deliberately NO policies at all: both submitting a ticket and reading the
-- admin inbox go through the service-role key from api/support/*.js routes
-- (submit.js runs unauthenticated on purpose — anyone should be able to
-- report a problem — but it still only ever touches this table via the
-- service-role client, never a user-supplied key). No anon/authenticated
-- client key should query this table directly, same rationale as
-- pdf_store_purchases.
